
IMAGE_PATH = './wbc_game_assistant/unit_images'

damage_types = {
    'slashing': '⚔️',
    'crushing': '🔨',
    'piercing': '🗡️',
    'fire': '🔥',
    'cold': '❄️',
    'electricity': '⚡',
    'magic': '📖'
  }


# DICT STRUCTURE:
# key: UNIT_ID
# values: [unit image name, unit ability]
unit_images_and_abilities = {
    # Fliers tier 1
    'AAEG': ['Eagle.jpg',
                'Flying, Can build all types of buildings, Triple damage vs large and huge fliers'],
    'AAPH': ['Phoenix.jpg', 'Flying, Can convert buildings'],
    'AALH': ['Lightning_Hawk.jpg', 'Flying'],
    'AABA': ['Bat.jpg',
                'Flying, Triple damage vs large and huge fliers'],
    'AADF': ['Dragonfly.jpg',
    'Flying, Poison (5), Triple damage vs large and huge fliers'],
    'AAFB': ['Firebat.jpg',
    'Flying, Triple damage vs large and huge fliers'],
    'AAWA': ['Wasp.jpg',
    'Flying, Poison (15), Assassination (4% + level), Triple damage vs large and huge fliers'],
    # Fliers tier 2
    'AARI': ['Griffon.jpg', 'Flying'],
    'AAPE': ['Pegasus.jpg', 'Flying'],
    'AAWY': ['Wyvern.jpg', 'Flying, Causes Fear (5)'],
    'AAPT': ['Pterodactyl.jpg', 'Flying'],
    'AAHA': ['Harpy.jpg',
    'Flying, Poison (5), Can cast Drain Mana (20 mana)'],
    # Fliers tier 3 - dragons
    'AADB': ['Storm_Dragon.jpg',
    'Flying, Splash damage drains mana, Terror (5)'],
    'AADR': ['Fire_Dragon.jpg',
    'Flying, Splash damage burns enemies, Terror (5)'],
    'AADG': ['Swamp_Dragon.jpg',
    'Flying, Splash damage lowers armor, Terror (5)'],
    'AADW': ['Frost_Dragon.jpg',
    'Flying, Splash damage freezes enemies, Terror (5)'],
    'AADC': ['Celestial_Dragon.jpg',
    'Flying, Splash damage crystalises enemies on their death, Terror (5), Double damage vs evil enemies'],
    'AADU': ['Dragonliche.jpg',
    'Flying, Splash damage takes away enemy XP, Terror (6), Double damage vs good enemies, Resistant to missiles'],
    # Elementals
    'AAEE': ['Earth_Elemental.jpg',
    'Quadruple damage vs Buildings, Causes Fear (5)'],
    'AAEA': ['Air_Elemental.jpg',
    'Can hit multiple opponents with each attack, Causes Fear (5), Can cross water'],
    'AAEW': ['Water_Elemental.jpg',
    'Causes Fear (5), Can cross water'],
    'AAEF': ['Fire_Elemental.jpg',
    'Can set opponents alight with each attack, Causes Fear (5)'],
    # Siege weapons
    'ADNX': ['Ballista.jpg',
    "The Ballista's projectiles can pass through multiple opponents"],
    'ASBA': ['Battering_Ram.jpg', '10x damage vs buildings'],
    'ASCA': ['Catapult.jpg',
    "The Catapult's projectiles do splash damage, Can pickup and throw Cows to do more damage"],
    'ASBC': ['Bone_Catapult.jpg', 'Splash damage'],
    # Common builder
    'AHBX': ['Peasant.jpg',
    'Can build all types of buildings, Can fill mines'],
    'ABBX': ['Thrall.jpg',
    'Can build all types of buildings, Can fill mines'],
    'AEBX': ['Wisp.jpg', 'Can build all types of buildings'],
    'AEAX': ['Ancient_Wisp.jpg',
    'Can build all types of buildings, Generates Crystal'],
    'AUBX': ['Zombie.jpg',
    'Can build all types of buildings, Can Fill Mines, Disease (5)'],
    # Dvarwes
    'ADBX': ['Dwarf_Smith.jpg',
    'Can build all types of buildings, Can Fill Mines, Counts as 2 men when placed in mines'],
    'ADSX': ['Dwarf_Runner.jpg', 'Resistant to normal missiles'],
    'ADIX': ['Dwarf_Infantry.jpg', 'Triple damage vs Elves'],
    'ADMX': ['Dwarf_Crossbow.jpg', None],
    'ADJX': ['Dwarf_Berserker.jpg', 'Triple damage vs Cavalry'],
    'ADLX': ['Khazrimi_Guard.jpg',
    'Increased chance of critical hits'],
    'ADOX': ['Runelord.jpg',
    'Can cast Doomstones (40 mana) and Stonecall (100 mana)'],
    'ADGX': ['Dwarf_Lord.jpg',
    'Resistant to Normal Missiles, Can convert Buildings, Double Damage vs Buildings'],
    'ATDX': ['King_Khalid.jpg',
    'Cause Terror (10), Ignores armor, Does not count as being a missile unit, Explodes into Rings of Fire upon death'],
    # Empire
    'AHIX': ['Pikeman.jpg', 'Triple damage vs cavalry'],
    'AHCX': ['Mercenary.jpg', None],
    'APMX': ['Archer.jpg', None],
    'AHJX': ['Halberdier.jpg', 'Triple damage vs cavalry'],
    'APDX': ['Elephant.jpg',
    'Double damage vs small units, Causes Fear (6)'],
    'AHGW': ['White_Mage.jpg',
    'Can convert buildings, Can cast Cure (30 mana) and Group Healing (40 mana)'],
    'AHGB': ['Black_Mage.jpg',
    'Can convert buildings, Gains 5 mana upon killing an enemy unit, Can cast Drain Mana (20 mana) and Hand of Ice (20 mana)'],
    'AHGR': ['Red_Mage.jpg',
    'Can convert buildings, Can cast Resist Fire (30 mana) and Ring of Fire (40 mana)'],
    'ATPX': ['The_Lion_Throne.jpg',
    'Causes Terror (10), Ignores armor, Explodes into Rings of Fire upon death'],
    # High Elves
    'AEIX': ['Iceguard.jpg', 'Triple damage vs. Dwarves'],
    'AEMX': ['Longbow.jpg', None],
    'AECX': ['DragonKnight.jpg', None],
    'AENX': ['Mystic.jpg',
    'Can cast Ring of Ice (40 mana) and White Ward (25 mana)'],
    'AEOX': ['IceMaiden.jpg',
    'Can cast Hand of Ice (20 mana) and Freeze (45 mana)'],
    'ASSC': ['Manticore.jpg',
    'Can cast Multishot (25 mana), Missiles deal splash damage and can carry through units to strike multiple targets'],
    'AEGX': ['Moonguard.jpg',
    'Can convert buildings, Can cast Multishot (25 mana)'],
    'ATEX': ['King_Lunarian.jpg',
    'Flying. Causes Terror (10), Ignores Armor'],
    # Knights
    'AHKX': ['Swordsman.jpg', None],
    'AHFX': ['Knight_Unit.jpg', None],
    'AHMX': ['Squire.jpg', None],
    'AHDX': ['Knight_Champion.jpg', None],
    'AHEX': ['Knight_Lord.jpg', 'Gives +2 Morale for your side'],
    'AHLX': ['Dancing_Sword.jpg', 'Can cross water'],
    'AAAR': ['Archon.jpg',
    'Flying, Can cast Cure (30 mana), Double damage vs. evil enemies, Causes Awe (10)'],
    'AHGX': ['Inquisitor.jpg',
    'Can convert buildings, Can cast Purify (50 mana) and Summon Blades (45 mana), Double damage vs evil enemies'],
    'ATHX': ['Sirian.jpg',
    'Causes Terror (10), Ignores armor, Splash damage, Explodes into Rings of Fire upon death'],
    # Barbarians
    'ABIX': ['Barbarian_Unit.jpg',
    'Spears travel through multiple enemies'],
    'ABCX': ['Rider.jpg', None],
    'ABDX': ['Wardog.jpg', 'Fast attack speed (+50%)'],
    'ABEX': ['Warlord.jpg', 'Gives +1 Morale to their side'],
    'ABGX': ['Reaver.jpg',
    'Triple damage vs large enemies, Can convert buildings'],
    'ATBX': ['Tempest.jpg',
    'Flying, Ignores Armor, Causes Terror (10), Explodes into Rings of Fire upon death'],
    # Fey
    'AFBX': ['Oakman.jpg',
    'Can build all types of buildings, Can fill mines'],
    'AFIX': ['Spriggan.jpg', 'Very fast attack speed (+100%)'],
    'AFJX': ['Sylph.jpg',
    'Can cross water, Fast attack speed (+50%)'],
    'AFMX': ['Faerie_Dragon.jpg', 'Flying'],
    'AFNX': ['Leprechaun.jpg', 'Generates gold as a level 1 mine'],
    'AASP': ['Sprite.jpg', 'Flying'],
    'AEXX': ['Pixie.jpg', 'Fast attack speed (+30%)'],
    'AEDX': ['Unicorn.jpg',
    'Can cast Cure (30 mana) and Group Healing (40 mana), Causes Awe (7)'],
    'AFGX': ['Banshee.jpg',
    'Can cross water, Causes Fear (5), Can cast Scare (40 mana), Can convert buildings, Splash damage'],
    'ATFX': ['Forestmaster.jpg',
    'Causes Terror (10), Ignores armor, Explodes into Rings of Ice upon death, Does not count as a missile unit'],
    #Minotaurs
    'AMIX': ['Minotaur_Infantry.jpg', 'Can eat animals to heal'],
    'AMNX': ['Axe_Thrower.jpg',
    'Axes can pass through multiple units, Can eat animals to heal'],
    'AOXX': ['Basilisk.jpg', 'Turns enemies it kills into 50 Stone'],
    'AMJX': ['Gnoll.jpg', 'Assassination (4% + level)'],
    'AMMX': ['Minotaur_Shaman.jpg',
    'Can cast Ring of Fire (40 mana), Pillar of Fire (40 mana) and Beserker (25 mana), Can eat animals to heal'],
    'AMGX': ['Minotaur_King.jpg',
    'Can convert buildings, Causes fear (5), Ignores armor, Can eat animals to heal'],
    'ATMX': ['Skull_of_Sartek.jpg',
    'Causes Terror (10), Ignores armor, Can eat animals to heal, Explodes into Rings of Fire upon death'],
    # Ssrathi
    'ALBX': ['Chameleon.jpg',
    'Can build all types of buildings, Can Fill Mines, Poison (6)'],
    'ALIX': ['Snakeman.jpg', 'Poison (7)'],
    'ALMX': ['Snakepriest.jpg',
    'Can cast Cauterise (30 mana) and Poison Cloud (25 mana)'],
    'ALCX': ['Lizard_Rider.jpg', 'Poison (5)'],
    'ALDX': ['Triceratops.jpg', None],
    'ALEX': ['Tyrannosaurus_Rex.jpg', 'Causes Fear (8)'],
    'ALGX': ['Naga.jpg',
    'Causes Fear (5), Can cast Defense Lore (40 mana), Can cross water'],
    'ATLX': ['Iriki.jpg',
    'Causes Terror (10), Ignores armor, Explodes into Rings of Fire upon death, Does not count as a missile unit'],
    # Wood Elves
    'AWIX': ['Forestguard.jpg', 'Triple damage vs Dwarves'],
    'AWMX': ['Gladewarden.jpg', None],
    'AWCX': ['Woodrider.jpg', 'Triple damage vs Orcish units'],
    'AEEX': ['Elven_Hunter.jpg', None],
    'AWNX': ['Druid.jpg',
    'Can cast Call Lightning (40 mana) and Rites to Dawn (40 mana)'],
    'AWJX': ['Treant.jpg',
    'Can build only main buildings, Can cast Entangle (20 mana)'],
    'AWKX': ['Ancient_Treant.jpg',
    'Splits into 2 Treants upon death, Can cast Entangle (20 mana)'],
    'AWGX': ['Dryad.jpg', 'Converts 25% faster than other generals'],
    'ATWX': ['Ironbark.jpg',
    'Causes Terror (10), Ignores armor, Splash damage, Explodes into Rings of Fire upon death'],
    #Daemons
    'AVBX': ['Daemon_Quasit.jpg',
    'Can build all types of buildings, Can Fill Mines, Poison (7)'],
    'AAIM': ['Daemon_Imp.jpg', 'Flying, Fast attack speed (+50%)'],
    'AVCX': ['Daemon_Nightmare.jpg', None],
    'AVIX': ['Daemon_Succubus.jpg',
    'Flying, Turns enemies into Souls upon their death'],
    'AVJX': ['Daemon_Reaper.jpg',
    'Can devour Souls to gain 20 XP (per soul)'],
    'AVDX': ['Daemon_Salamander.jpg',
    'Splash damage, Causes Fear (5)'],
    'AADE': ['Daemon_Daemon.jpg',
    'Can Summon Imps (40 mana), Flying, Causes Chaos (9), Devours Souls for 25 mana, Double damage vs. good units'],
    'AVGX': ['Daemon_Summoner.jpg',
    'Can convert buildings, Can cast Daemon Gate (100 mana)  and Banish (30 mana), Devours Souls for 25 mana'],
    'ATVX': ['Balora.jpg',
    'Flying, Causes Terror (10), Ignores armor, Splash damage, Explodes into Rings of Ice upon death'],
    #Dark Elves
    'AKIX': ['Dark_Infantry.jpg', 'Triple damage vs Dwarves'],
    'AKKX': ['Spider.jpg', 'Poison (12)'],
    'AKMX': ['Dark_Archer.jpg',
    'Arrows inflict Poison (strength = damage / 2, making 6 by default)'],
    'AKCX': ['Dark_Rider.jpg', 'Triple damage vs Heroes'],
    'AKLX': ['Queen_Spider.jpg',
    'Poison (15), Lays eggs in slain victims'],
    'AKNX': ['Sorceror.jpg',
    'Can raise Zombies (45 mana), Can cast Pillar of Fire (40 mana) and Darkstorm (40 mana)'],
    'AKOX': ['Spider_Priestess.jpg',
    'Can summon Queen Spiders (45 mana), Turns into 6 Spiders upon death'],
    'AKJX': ['Assassin.jpg',
    'Assassination (4% + level), Poison (20), Fast attack speed (+50%'],
    'AKGX': ['Black_Guard.jpg',
    'Can cast Invisibility (35 mana), Can convert buildings, Poison (10)'],
    'ATKX': ['Kargoth.jpg',
    'Causes Terror (10), Ignores armor, Explodes into Rings of Ice upon death'],
    #Dark Dvarwes
    'AABX': ['Engineer.jpg',
    'Can build all types of buildings, Counts as 2 men when placed in a mine'],
    'AAIX': ['Stone_Golem.jpg', 'Slow attack speed (-30%)'],
    'AAJX': ['Iron_Golem.jpg',
    'Attacks hit multiple opponents, Slow attack speed (-20%), Can summon Firebombs (35 mana)'],
    'AASX': ['Firebomb.jpg',
    'Explodes when it attacks or is killed causing splash damage (in the 8 spaces around the unit)'],
    'AAMX': ['Flame_Cannon.jpg', None],
    'AANX': ['Hellbore.jpg', None],
    'AAGX': ['Bronze_Golem.jpg',
    'Can convert buildings, Can scavenge building rubble for resources'],
    'ATAX': ['Grond.jpg',
    'Causes Terror (10), Ignores Armor, Splash damage, Explodes into Rings of Ice upon death'],
    # Orcs
    'AOBX': ['Kobold.jpg',
    'Can build all types of buildings, Can Fill Mines, Poison (6)'],
    'AOIX': ['Orc_Unit.jpg', None],
    'AOSX': ['Goblin.jpg', 'Disease (7)'],
    'ASGS': ['Gobshooter.jpg',
    'Splash Damage, 12.5% chance to spawn a Goblin on hit'],
    'AOCX': ['WolfRider.jpg', None],
    'AOOX': ['Kolbold_Sniper.jpg', None],
    'AOJX': ['Ogre.jpg', None],
    'AOMX': ['Troll.jpg',
    'Can pick up and throw Sheep, 400% HP regeneration'],
    'AOKX': ['Goblin_Chief.jpg',
    'Can summon a group of Goblins (75 mana)'],
    'AONX': ['Goblin_Shaman.jpg',
    'Can cast Call Lightning (40 mana), Berserker (25 mana) and Light/Darkness (50 mana)'],
    'AOGX': ['Giant.jpg',
    'Can convert buildings, Hits multiple enemies with each strike (spread/splash damage), \n                Causes Fear (9)'],
    'ATOX': ['Gornak_Elfeater.jpg',
    'Causes Terror (10), Ignores Armour, Petrifies enemies it kills into 50 stone, Explodes into Rings of Fire upon death, \n                Does not count as a missile unit'],
    # Plaguelords
    'AGPC': ['Ghoul.jpg', None],
    'AGSL': ['Slime.jpg', None],
    'AGGZ': ['Gazer.jpg', None],
    'AGHY': ['Hydra.jpg', 'Splash damage, Causes Fear (5)'],
    'AGSP': ['Spore.jpg', None],
    'AGCY': ['Cryohydra.jpg', 'Splash damage, Causes Fear (5)'],
    'AGFL': ['Eye_of_Flame.jpg',
    'Splash damage that sets enemies alight, Can cross water, Immune to Disease'],
    'AGPY': ['Pyrohydra.jpg', 'Splash damage, Causes Fear (5)'],
    'AGGX': ['Plague_Priest.jpg',
    'Can convert buildings, Casts Eye of Oros (30 mana) and Plague Cloud (55 mana) spells, Immune to Disease'],
    'ATGX': ['Lord_Antharg.jpg',
    'Causes Terror (10), Ignores Armor, Splash damage, Explodes into Rings of Ice upon death'],
    # Swarm
    'ARBX': ['Ant.jpg',
    'Can build all types of buildings, Can fill mines'],
    'ARJX': ['Husk.jpg', 'Highly resistant to missiles'],
    'ARMX': ['Scarab.jpg', None],
    'ARIX': ['Scorpion.jpg', 'Poison (10), Fast attack speed (+50%)'],
    'ARCX': ['Scorpionman.jpg', 'Poison (15)'],
    'ARGX': ['Scorpionpriest.jpg',
    'Can convert buildings, Can cast Ring of Fire (40 mana), Can Summon Fire Elementals (100 mana)'],
    'ATRX': ['Lord_Melkor.jpg',
    'Causes Terror (10), Ignores armor,  Splash damage, Explodes into Rings of Fire upon death'],
    #Undead
    'AUIX': ['Skeleton.jpg', 'Resistant to missiles'],
    'AUJX': ['Wight.jpg', None],
    'AUKX': ['Wraith.jpg', 'Drains EXP from enemies it kills'],
    'AULX': ['Slayer_Knight.jpg', 'Cause Chaos (9)'],
    'AUCX': ['SkeletonCavalry.jpg', 'Resistant to missiles'],
    'AUXX': ['Shadow.jpg',
    'Drains EXP from enemies it kills, +5 combat at night (+7 including their racial bonus)'],
    'AUAX': ['DoomKnight.jpg', 'Cause Chaos (12)'],
    'AUMX': ['Liche.jpg', 'Can cast Call the Dead (45 mana)'],
    'AUGX': ['Vampire.jpg',
    'Can summon Bats (40 mana), Can convert buildings, Vampirism, Causes Fear (8)'],
    'ATUX': ['Lord_Bane.jpg',
    'Causes Terror (10), Ignores armor, Explodes into Rings of Ice upon death']

}
